version: '3.8'

services:
  backend:
    build: ./server
    container_name: myrecipes-backend
    ports:
      - "3001:3001"
    volumes:
      - ./server/db:/app/db
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: myrecipes-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
